### ISSUE TITLE
Python: Cursor hangs when using Send Selection to Terminal when using Folder as a workspace

### ISSUE THREAD

**Issue by AdroMine** [vscode-neovim/vscode-neovim#1007]
While using python, I have enabled keyboard shortcut to send selection to terminal via Shift + Enter. To enable the same when using this extension, I have added the following lines to `init.vim` & `keybindings.json`

#### init.vim
``` 
xnoremap <S-CR> <Cmd>call VSCodeNotifyVisual('python.execSelectionInTerminal',1)<CR>
```
#### keybindings.json
``` json
    { 
        "key": "shift+enter",
        "command": "vscode-neovim.send",
        "when": "editorTextFocus && neovim.mode == visual",
        "args": "<S-CR>" 
    },
    {
        "key": "shift+enter",
        "command": "-python.execSelectionInTerminal",
        "when": "editorTextFocus && !findInputFocussed && !replaceInputFocussed && editorLangId == 'python'"
    },

```

Using the above settings, I am able to use neovim to visually select multiple lines, or part of line and press shift+enter to run them in terminal successfully. 

However, when I use the "Open Folder" option in VSCode to open some folder as workspace and then try to send selection to terminal, then Neovim's cursor stops moving and nothing is sent to terminal. After that, even if I move the cursor using mouse, neovim doesn't detect that, so if I then start visual selection, it would start from someplace other than where the cursor would be (as in the screenshot below)

<img src="https://user-images.githubusercontent.com/12209206/184535546-aa27e8fb-0fce-40f7-98b2-0074da8f5836.png" width = 600>

> (in above snap, cursor is on line 12, but visual selection starts from line 3, where I tried the shift+enter). If I switch to insert mode, typing starts from where the cursor is (line 12 in above case).

### Output of "Log (Extension Host)"

<details>

``` bat
[2022-08-14 17:02:32.635] [exthost] [error] Error: 
	at w.cmp (d:\Software\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:62:65516)
	at b.findSubstr (d:\Software\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:62:69539)
	at h.getWorkspaceFolder (d:\Software\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:14351)
	at S.getWorkspaceFolder (d:\Software\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:96:17203)
	at Object.getWorkspaceFolder (d:\Software\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:45086)
	at c.getWorkspaceFolder (c:\Users\adromine\.vscode\extensions\ms-python.python-2022.12.0\out\client\extension.js:2:122633)
	at Function.getSettingsUriAndTarget (c:\Users\adromine\.vscode\extensions\ms-python.python-2022.12.0\out\client\extension.js:2:127079)
	at Function.getInstance (c:\Users\adromine\.vscode\extensions\ms-python.python-2022.12.0\out\client\extension.js:2:126569)
	at h.getSettings (c:\Users\adromine\.vscode\extensions\ms-python.python-2022.12.0\out\client\extension.js:2:137862)
	at _.getActiveInterpreter (c:\Users\adromine\.vscode\extensions\ms-python.python-2022.12.0\out\client\extension.js:2:467667)
	at c:\Users\adromine\.vscode\extensions\ms-python.python-2022.12.0\out\client\extension.js:2:691160
	at a._executeContributedCommand (d:\Software\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:63922)
	at a._doExecuteCommand (d:\Software\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:62740)
	at a.executeCommand (d:\Software\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:85:62600)
	at Object.executeCommand (d:\Software\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:106:31928)
	at ve.<anonymous> (c:\Users\adromine\.vscode\extensions\asvetliakov.vscode-neovim-0.0.89\dist\extension.js:2:216791)
	at Generator.next (<anonymous>)
	at c:\Users\adromine\.vscode\extensions\asvetliakov.vscode-neovim-0.0.89\dist\extension.js:2:209543
	at new Promise (<anonymous>)
	at pe (c:\Users\adromine\.vscode\extensions\asvetliakov.vscode-neovim-0.0.89\dist\extension.js:2:209288)
	at ve.handleVSCodeRangeCommand (c:\Users\adromine\.vscode\extensions\asvetliakov.vscode-neovim-0.0.89\dist\extension.js:2:216303)
	at c:\Users\adromine\.vscode\extensions\asvetliakov.vscode-neovim-0.0.89\dist\extension.js:2:249062
	at Array.forEach (<anonymous>)
	at o.Ne.onNeovimNotification (c:\Users\adromine\.vscode\extensions\asvetliakov.vscode-neovim-0.0.89\dist\extension.js:2:249043)
	at o.emit (node:events:390:28)
	at o.emitNotification (c:\Users\adromine\.vscode\extensions\asvetliakov.vscode-neovim-0.0.89\dist\extension.js:2:51959)
	at o.handleNotification (c:\Users\adromine\.vscode\extensions\asvetliakov.vscode-neovim-0.0.89\dist\extension.js:2:52077)
	at a.emit (node:events:390:28)
	at a.parseMessage (c:\Users\adromine\.vscode\extensions\asvetliakov.vscode-neovim-0.0.89\dist\extension.js:2:67824)
	at c:\Users\adromine\.vscode\extensions\asvetliakov.vscode-neovim-0.0.89\dist\extension.js:2:67361
	at processTicksAndRejections (node:internal/process/task_queues:96:5) python.execSelectionInTerminal {"value":"ms-python.python","_lower":"ms-python.python"}
```
</details>

I have tried with a clean init.vim and disabling all other extensions (except Python extension), but I still get the same error.

**Comment by theol0403** [comment]
Sorry, I don't quite understand. This issue happens while "Open Folder" is open? Or the issue happens after you open a new window?

**Comment by AdroMine** [comment]
Sorry for not being clear. The issue happens when I open a folder as a workspace. 
In VSCode, use `File Menu -> Open Folder` and then edit some python file within that folder.

**Comment by milesfj** [comment]
Yes, can confirm I have the same problem. When I am not in a folder I can send multiple lines to be executed in the terminal but when open a folder and try to run multiple lines it freezes. Is there anyway around this or another way to execute selection in terminal?
