### ISSUE TITLE
bug: After plugin update, text editing in Python stops works

### ISSUE THREAD

**Issue by mkubasz** [vscode-neovim/vscode-neovim#1907]
### Check the following:

- [X] I have checked the behavior after setting "vscode-neovim.neovimClean" in VSCode settings.
- [X] I have read the vscode-neovim docs.
- [X] I have searched existing issues.

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

MacOS 14.4.1

### Describe the bug

With the new version of the plugin I'm not able to write anything in Explorer and Editor. After moving to Python file. Something blocked it, even if I backed to other type of file.
I remove and clear VSCode event with .vscode.

https://github.com/vscode-neovim/vscode-neovim/assets/1952619/5a1e22bc-2c3c-425a-bc5d-6ef5f01064ed

### Steps To Reproduce

1. Instal neovim plugin
2. Go to Python file
3. Try to write something
4. Move to other file with different type
5. Try to write something

### Expected Behavior

Should normally works with inserting, visual etc

**Comment by xiyaowong** [comment]
Need log.

**Comment by mkubasz** [comment]
@xiyaowong 
Logs I found in python file
```
2024-04-27 21:06:44.780 [info] BufferManager: Visible editor, viewColumn: 1, doc: file:///Users/x/Projects/rest-client/main.py
2024-04-27 21:06:44.781 [info] BufferManager: Document not known, init in neovim
2024-04-27 21:06:44.781 [info] BufferManager: Init buffer for 2, doc: file:///Users/x/Projects/rest-client/main.py
2024-04-27 21:06:54.259 [info] BufferManager: Visible editor, viewColumn: 1, doc: file:///Users/x/Projects/rest-client/main.py
2024-04-27 21:06:54.259 [info] BufferManager: Document not known, init in neovim
```
In not python file

```
2024-04-27 21:07:44.423 [info] MainController: Init completed
2024-04-27 21:07:44.527 [info] BufferManager: Visible editor, viewColumn: 1, doc: file:///Users/x/Projects/rest-client/requirements.txt
2024-04-27 21:07:44.527 [info] BufferManager: Document not known, init in neovim
2024-04-27 21:07:44.527 [info] BufferManager: Init buffer for 2, doc: file:///Users/x/Projects/rest-client/requirements.txt
2024-04-27 21:07:44.533 [info] DocumentChangeManager: Init buffer content for bufId: 2, uri: file:///Users/x/Projects/rest-client/requirements.txt
2024-04-27 21:07:44.533 [info] BufferManager: Document: file:///Users/x/Projects/rest-client/requirements.txt, BufId: 2
2024-04-27 21:07:44.533 [info] BufferManager: Creating new window for 1 column (undefined is OK here)
2024-04-27 21:07:44.536 [info] BufferManager: Created new window: 1002 ViewColumn: 1
2024-04-27 21:07:44.545 [info] BufferManager: Setting active editor - viewColumn: 1, winId: 1002
2024-04-27 21:07:44.649 [info] BufferManager: window changed, target window id: 1002
2024-04-27 21:07:45.435 [info] ModeManager: Changing mode to i
2024-04-27 21:07:45.435 [info] ModeManager: Setting mode context to insert
2024-04-27 21:07:45.435 [info] TypingManager: Waiting for cursor completion operation before disposing type handler
2024-04-27 21:07:45.436 [info] TypingManager: Disabling type handler
2024-04-27 21:07:45.436 [info] TypingManager: Disabling replacePrevChar handler
```

Moving from txt to python only for few types working

```
2024-04-27 21:07:44.423 [info] MainController: Init completed
2024-04-27 21:07:44.527 [info] BufferManager: Visible editor, viewColumn: 1, doc: file:///Users/x/Projects/rest-client/requirements.txt
2024-04-27 21:07:44.527 [info] BufferManager: Document not known, init in neovim
2024-04-27 21:07:44.527 [info] BufferManager: Init buffer for 2, doc: file:///Users/x/Projects/rest-client/requirements.txt
2024-04-27 21:07:44.533 [info] DocumentChangeManager: Init buffer content for bufId: 2, uri: file:///Users/x/Projects/rest-client/requirements.txt
2024-04-27 21:07:44.533 [info] BufferManager: Document: file:///Users/x/Projects/rest-client/requirements.txt, BufId: 2
2024-04-27 21:07:44.533 [info] BufferManager: Creating new window for 1 column (undefined is OK here)
2024-04-27 21:07:44.536 [info] BufferManager: Created new window: 1002 ViewColumn: 1
2024-04-27 21:07:44.545 [info] BufferManager: Setting active editor - viewColumn: 1, winId: 1002
2024-04-27 21:07:44.649 [info] BufferManager: window changed, target window id: 1002
2024-04-27 21:07:45.435 [info] ModeManager: Changing mode to i
2024-04-27 21:07:45.435 [info] ModeManager: Setting mode context to insert
2024-04-27 21:07:45.435 [info] TypingManager: Waiting for cursor completion operation before disposing type handler
2024-04-27 21:07:45.436 [info] TypingManager: Disabling type handler
2024-04-27 21:07:45.436 [info] TypingManager: Disabling replacePrevChar handler
2024-04-27 21:08:26.809 [info] BufferManager: Editor viewColumn: 1, winId: 1002, closing
2024-04-27 21:08:26.809 [info] BufferManager: Document: file:///Users/x/Projects/rest-client/requirements.txt, bufId: 2, deleting
2024-04-27 21:08:26.810 [info] BufferManager: Visible editor, viewColumn: 1, doc: file:///Users/x/Projects/rest-client/main.py
2024-04-27 21:08:26.810 [info] BufferManager: Document not known, init in neovim
2024-04-27 21:08:26.810 [info] BufferManager: Init buffer for 4, doc: file:///Users/x/Projects/rest-client/main.py
2024-04-27 21:08:28.951 [warning] DocumentChangeManager: Can't get last known neovim content for file:///Users/x/Projects/rest-client/main.py, skipping
2024-04-27 21:08:28.952 [warning] DocumentChangeManager: Can't get last known neovim content for file:///Users/x/Projects/rest-client/main.py, skipping
2024-04-27 21:08:29.537 [warning] DocumentChangeManager: Can't get last known neovim content for file:///Users/x/Projects/rest-client/main.py, skipping
2024-04-27 21:08:29.804 [warning] DocumentChangeManager: Can't get last known neovim content for file:///Users/x/Projects/rest-client/main.py, skipping
2024-04-27 21:08:30.303 [warning] DocumentChangeManager: Can't get last known neovim content for file:///Users/x/Projects/rest-client/main.py, skipping
2024-04-27 21:08:30.552 [warning] DocumentChangeManager: Can't get last known neovim content for file:///Users/x/Projects/rest-client/main.py, skipping
2024-04-27 21:08:30.726 [warning] DocumentChangeManager: Can't get last known neovim content for file:///Users/x/Projects/rest-client/main.py, skipping
2024-04-27 21:08:30.918 [warning] DocumentChangeManager: Can't get last known neovim content for file:///Users/x/Projects/rest-client/main.py, skipping
2024-04-27 21:08:31.559 [warning] DocumentChangeManager: Can't get last known neovim content for file:///Users/x/Projects/rest-client/main.py, skipping
2024-04-27 21:08:31.933 [warning] DocumentChangeManager: Can't get last known neovim content for file:///Users/x/Projects/rest-client/main.py, skipping
2024-04-27 21:08:32.306 [warning] DocumentChangeManager: Can't get last known neovim content for file:///Users/x/Projects/rest-client/main.py, skipping
2024-04-27 21:08:32.307 [warning] DocumentChangeManager: Can't get last known neovim content for file:///Users/x/Projects/rest-client/main.py, skipping
2024-04-27 21:08:34.086 [info] TypingManager: Enabling type handler
2024-04-27 21:08:34.086 [info] TypingManager: Enabling replacePrevChar handler
2024-04-27 21:08:34.086 [info] TypingManager: Send for: <Esc>
2024-04-27 21:08:34.461 [info] TypingManager: Send for: <Esc>
2024-04-27 21:08:36.013 [info] TypingManager: Send for: <Esc>
2024-04-27 21:08:37.319 [info] TypingManager: Send for: <Esc>
2024-04-27 21:08:37.578 [info] TypingManager: Send for: <Esc>
2024-04-27 21:08:39.482 [warning] DocumentChangeManager: Can't get last known neovim content for file:///Users/x/Projects/rest-client/main.py, skipping
2024-04-27 21:08:39.482 [warning] DocumentChangeManager: Can't get last known neovim content for file:///Users/x/Projects/rest-client/main.py, skipping
2024-04-27 21:08:39.886 [warning] DocumentChangeManager: Can't get last known neovim content for file:///Users/x/Projects/rest-client/main.py, skipping
2024-04-27 21:08:39.886 [warning] DocumentChangeManager: Can't get last known neovim content for file:///Users/x/Projects/rest-client/main.py, skipping
2024-04-27 21:08:41.528 [warning] DocumentChangeManager: Can't get last known neovim content for file:///Users/x/Projects/rest-client/main.py, skipping
2024-04-27 21:08:41.529 [warning] DocumentChangeManager: Can't get last known neovim content for file:///Users/x/Projects/rest-client/main.py, skipping
2024-04-27 21:08:42.196 [warning] DocumentChangeManager: Can't get last known neovim content for file:///Users/x/Projects/rest-client/main.py, skipping
2024-04-27 21:08:42.197 [warning] DocumentChangeManager: Can't get last known neovim content for file:///Users/x/Projects/rest-client/main.py, skipping
```

Some window log
```
      󰌱 editSessions.log  ▕   󰌱 network.log    ▕ 󰌱 notebook.renderin…  ▕▎ 󰌱 renderer.log   ▏ 󰌱 vscode-neovim.log  ▕     󰌱 Git.log      ▕   󰌱 GitHub.log    ▕ 󰌱 extensionTelemetr…  ▕ 󰌱 GitHub Authentica…   8 
  ~/Library/Application Support/Code/lo│  1   2024-04-27 20:58:49.548 [info] Started local extension host with pid 40402.
   window1                            │  1   2024-04-27 20:58:49.563 [info] Placing extension(s) asvetliakov.vscode-neovim on a separate extension host.
     exthost                          │  2   2024-04-27 20:58:49.670 [info] Started local extension host with pid 40403.
   │   asvetliakov.vscode-neovim      │  3   2024-04-27 20:58:50.022 [error] Cannot read properties of undefined (reading 'accessToken'): TypeError: Cannot read properties of undefined (reading 'accessToken')
   │ │ └ 󰌱 vscode-neovim.log            │  4       at b.h (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1693:21270)
   │   vscode.git                     │  5       at b.j (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1693:22006)
   │ │ └ 󰌱 Git.log                      │  6       at u.value (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1693:21027)
   │   vscode.github                  │  7   2024-04-27 20:58:52.162 [info] [perf] Render performance baseline is 15ms
   │ │ └ 󰌱 GitHub.log                   │
   ```

**Comment by mkubasz** [comment]
Sorry for trouble, the problem was with neovim.
