### ISSUE TITLE
test/ci: failing test "highlights forward search / for long line"

### ISSUE THREAD

**Issue by justinmk** [vscode-neovim/vscode-neovim#2329]
```
  1) Test highlights
       forward search / for long line:
     Error: Extension 'asvetliakov.vscode-neovim' CANNOT use API proposal: nativeWindowHandle.
Its package.json#enabledApiProposals-property declares: [] but NOT nativeWindowHandle.
 The missing proposal MUST be added and you must start in extension development mode or use the following command line switch: --enable-proposed-api asvetliakov.vscode-neovim
      at L (file:///d:/a/vscode-neovim/vscode-neovim/.vscode-test/vscode-win32-x64-archive-1.96.0/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:113:16650)
      at Object.get nativeHandle [as nativeHandle] (file:///d:/a/vscode-neovim/vscode-neovim/.vscode-test/vscode-win32-x64-archive-1.96.0/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:157:50586)
      at Function.assign (<anonymous>)
      at d:\a\vscode-neovim\vscode-neovim\src\test\integ\highlights.test.ts:97:25
```

https://github.com/vscode-neovim/vscode-neovim/blob/e0eba53505efbffbf7c046fb347a915b14bebdd0/src/test/integ/highlights.test.ts#L97-L102

Maybe we need to use `sinon` instead of overwriting `vscode.window` @xiyaowong

**Comment by justinmk** [comment]
Can't reproduce this locally...
