### ISSUE TITLE
How to run tests?

### ISSUE THREAD

**Issue by BKStephens** [vscode-neovim/vscode-neovim#815]
I cloned the repository and ran:

```
yarn install
...
yarn test
yarn run v1.22.17
warning vscode-neovim@0.0.83: The engine "vscode" appears to be invalid.
$ yarn run test-compile
warning vscode-neovim@0.0.83: The engine "vscode" appears to be invalid.
$ tsc -p ./
$ node ./out/test/runTest.js
Found .vscode-test/vscode-darwin-1.63.2. Skipping download.
[main 2022-01-28T18:10:48.513Z] update#setState idle

[main 2022-01-28T18:10:48.738Z] ExtensionHostStarterWorker created

2022-01-28 10:10:50.780 Code Helper (Renderer)[29235:127733] CoreText note: Client requested name ".NewYork-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2022-01-28 10:10:50.780 Code Helper (Renderer)[29235:127733] CoreText note: Set a breakpoint on CTFontLogSystemFontNameRequest to debug.

[main 2022-01-28T18:10:53.132Z] Starting extension host with pid 29259 (fork() took 88 ms).

(node:29259) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Electron --trace-deprecation ...` to show where the warning was created)

rejected promise not handled within 1 second: Error: command 'type' already exists

stack trace: Error: command 'type' already exists
    at registerCommand (/Users/bstephens-mac/repos/vscode-neovim/.vscode-test/vscode-darwin-1.63.2/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:29537)
    at Object.registerCommand (/Users/bstephens-mac/repos/vscode-neovim/.vscode-test/vscode-darwin-1.63.2/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:21205)
    at overrideCommand (/Users/bstephens-mac/.vscode/extensions/vscodevim.vim-1.21.10/extensionBase.ts:569:38)
    at t.activate (/Users/bstephens-mac/.vscode/extensions/vscodevim.vim-1.21.10/extensionBase.ts:362:3)
command 'type' already exists: Error: command 'type' already exists
    at registerCommand (/Users/bstephens-mac/repos/vscode-neovim/.vscode-test/vscode-darwin-1.63.2/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:95:29537)
    at Object.registerCommand (/Users/bstephens-mac/repos/vscode-neovim/.vscode-test/vscode-darwin-1.63.2/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:21205)
    at overrideCommand (/Users/bstephens-mac/.vscode/extensions/vscodevim.vim-1.21.10/extensionBase.ts:569:38)
    at t.activate (/Users/bstephens-mac/.vscode/extensions/vscodevim.vim-1.21.10/extensionBase.ts:362:3)



  Basic editing and navigation

rejected promise not handled within 1 second: Error: connect ECONNREFUSED 127.0.0.1:4000

stack trace: Error: connect ECONNREFUSED 127.0.0.1:4000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
connect ECONNREFUSED 127.0.0.1:4000: Error: connect ECONNREFUSED 127.0.0.1:4000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)

Error while registering log channel file:///Users/bstephens-mac/Library/Application%20Support/Code/logs/20220128T101047/userDataSync.log Timed out while waiting for file to be created

[main 2022-01-28T18:11:18.519Z] update#setState checking for updates

[main 2022-01-28T18:11:18.756Z] update#setState idle
```

Am I supposed to have something running on port 4000 for `yarn test` to work?:
```
stack trace: Error: connect ECONNREFUSED 127.0.0.1:4000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
connect ECONNREFUSED 127.0.0.1:4000: Error: connect ECONNREFUSED 127.0.0.1:4000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
```

**Comment by trkoch** [comment]
I suppose tests expect `127.0.0.1:4000` to provide an Neovim instance. Is `nvim` in your path and does it come up properly?

**Comment by BKStephens** [comment]
> Is nvim in your path and does it come up properly?

Yes

```
which nvim
/opt/homebrew/bin/nvim
```

But nothing is using port 4000 locally:
```
sudo lsof -i -P | grep 4000
```

I can see that CI for the project is installing nvim from here: https://github.com/vscode-neovim/vscode-neovim/blob/master/.github/workflows/build_test.yml#L23-L28

What I am still trying to figure out is how CI starts a nvim debug process that is using port 4000. I looked in https://github.com/rhysd/action-setup-vim but havn't found anything yet.

**Comment by justinmk** [comment]
This works for me:

```
nvim --listen 127.0.0.1:4000
./node_modules/.bin/yarn run test
```

The `test` task should probably be enhanced to start `nvim` if needed.

**Comment by theol0403** [comment]
> This works for me:
> 
> ```
> nvim --listen 127.0.0.1:4000
> ./node_modules/.bin/yarn run test
> ```
> 
> The `test` task should probably be enhanced to start `nvim` if needed.

Actually, this doesn't work. This spawns a new nvim instance, but this is not the nvim instance that vscode actually uses for the buffers. This causes the tests to fail, because all tests read an empty nvim buffer.

The solution is to actually just set `export NEOVIM_DEBUG=1` before running `yarn run test`, which creates a nvim server at the default address `127.0.0.1:4000`. The ext defaults to that address.

https://github.com/vscode-neovim/vscode-neovim/blob/e78b82ef379f5d4b759f4cdffb28dd9c65133d70/src/test/utils.ts#L33

Btw, you can use the vscode debugger to run the extension from source without needing to make vsix and also run tests - then you can run it with `F5`.

**Comment by theol0403** [comment]
Info added to readme.
